# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_admin', '0002_remove_user_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SystemUser',
        ),
    ]
